import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import { resolveRoot } from '../utils/glob.js';

export interface GenerateValidatorOptions {
  exampleFile: string;
  output: string;
  typescript: boolean;
  noColor: boolean;
  root: string;
}

async function parseExampleKeys(filePath: string): Promise<string[]> {
  let content: string;
  try {
    content = await readFile(filePath, 'utf-8');
  } catch {
    throw new Error(`Could not read ${filePath} — run env-doctor init first`);
  }
  const keys: string[] = [];
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    const key = (eq === -1 ? trimmed : trimmed.slice(0, eq)).trim();
    if (key) keys.push(key);
  }
  return keys;
}

function generateJS(keys: string[]): string {
  return `// Auto-generated by env-doctor — do not edit manually
// Add this at the top of your app entry file (index.js, server.js, etc.)
// Re-generate with: npx @neerav34/env-doctor generate-validator

const REQUIRED_ENV_VARS = ${JSON.stringify(keys, null, 2)};

const missing = REQUIRED_ENV_VARS.filter((key) => !process.env[key]);

if (missing.length > 0) {
  console.error('[env-doctor] Missing required environment variables:');
  missing.forEach((key) => console.error(\`  - \${key}\`));
  console.error('[env-doctor] Add them to your environment and restart the app.');
  process.exit(1);
}
`;
}

function generateTS(keys: string[]): string {
  return `// Auto-generated by env-doctor — do not edit manually
// Add this at the top of your app entry file (index.ts, server.ts, etc.)
// Re-generate with: npx @neerav34/env-doctor generate-validator

const REQUIRED_ENV_VARS: string[] = ${JSON.stringify(keys, null, 2)};

const missing = REQUIRED_ENV_VARS.filter((key) => !process.env[key]);

if (missing.length > 0) {
  console.error('[env-doctor] Missing required environment variables:');
  missing.forEach((key: string) => console.error(\`  - \${key}\`));
  console.error('[env-doctor] Add them to your environment and restart the app.');
  process.exit(1);
}
`;
}

export async function runGenerateValidator(opts: GenerateValidatorOptions): Promise<void> {
  const root = resolveRoot(opts.root);
  const examplePath = path.resolve(root, opts.exampleFile);
  const keys = await parseExampleKeys(examplePath);

  if (keys.length === 0) {
    process.stdout.write('\n  No variables found in .env.example — nothing to generate.\n\n');
    return;
  }

  const code = opts.typescript ? generateTS(keys) : generateJS(keys);
  const ext = opts.typescript ? 'ts' : 'js';
  const outFile = opts.output || `env-validator.${ext}`;
  const outPath = path.resolve(root, outFile);

  await writeFile(outPath, code, 'utf-8');

  process.stdout.write(`
  Generated runtime validator → ${outFile}

  Add this line at the top of your entry file:

    ${opts.typescript ? `import './${outFile}';` : `require('./${outFile}');`}

  ${keys.length} variable${keys.length === 1 ? '' : 's'} will be checked at startup: ${keys.join(', ')}

  Re-generate after changing .env.example:
    npx @neerav34/env-doctor generate-validator

`);
}
