import path from 'path';
import { writeFile, readFile } from 'fs/promises';
import { parseEnvFile } from '../core/parser.js';
import { scanProjectFiles } from '../core/scanner.js';
import { detectVarsInFile } from '../core/detector.js';
import { setColorEnabled, logger } from '../utils/logger.js';
import { resolveRoot } from '../utils/glob.js';
import type { InitOptions, EnvVarReference, EnvVarDefinition } from '../types/index.js';

export async function runInit(options: InitOptions): Promise<void> {
  setColorEnabled(!options.noColor);

  const root = resolveRoot(options.root);
  const envFilePath = path.resolve(root, options.envFile);
  const exampleFilePath = path.resolve(root, options.exampleFile);

  logger.header('\n  Generating .env.example...\n');

  const start = Date.now();

  // Parse existing files
  const [envResult, existingExampleResult] = await Promise.all([
    parseEnvFile(envFilePath, false),
    parseEnvFile(exampleFilePath, true),
  ]);

  // Scan and detect all env var references
  const { files } = await scanProjectFiles(root, {
    ignore: options.ignore,
    respectGitignore: true,
  });

  const refResults = await Promise.allSettled(
    files.map(file => detectVarsInFile(root, file))
  );

  // Collect unique variable names and their first references
  const foundVarsMap = new Map<string, EnvVarReference>();
  for (const result of refResults) {
    if (result.status !== 'fulfilled') continue;
    for (const ref of result.value) {
      if (!foundVarsMap.has(ref.name)) {
        foundVarsMap.set(ref.name, ref);
      }
    }
  }

  const allVarNames = new Set([
    ...foundVarsMap.keys(),
    ...envResult.vars.keys(),
  ]);

  // Determine what's new vs already present
  const existingNames = new Set(existingExampleResult.vars.keys());
  const newVars: string[] = [];
  const presentVars: string[] = [];

  for (const name of allVarNames) {
    if (existingNames.has(name)) {
      presentVars.push(name);
    } else {
      newVars.push(name);
    }
  }

  if (newVars.length === 0 && existingExampleResult.exists) {
    logger.success(`  ✓  .env.example is already up to date (${presentVars.length} variable${presentVars.length === 1 ? '' : 's'})\n`);
    return;
  }

  const content = buildExampleContent({
    existingContent: existingExampleResult.exists
      ? await readFile(exampleFilePath, 'utf-8').catch(() => '')
      : null,
    newVars,
    presentVars,
    foundVarsMap,
    envVars: envResult.vars,
    withComments: options.withComments,
  });

  await writeFile(exampleFilePath, content, 'utf-8');

  const duration = Date.now() - start;

  logger.success(
    `  ✓  ${existingExampleResult.exists ? 'Updated' : 'Created'} ${options.exampleFile}` +
    ` with ${allVarNames.size} variable${allVarNames.size === 1 ? '' : 's'}` +
    ` (${newVars.length} new, ${presentVars.length} already present)\n`
  );

  if (newVars.length > 0) {
    logger.bold('  New variables added:');
    for (const name of newVars.sort()) {
      const ref = foundVarsMap.get(name);
      const loc = ref ? logger.dim_(`  # from ${ref.file}:${ref.line}`) : '';
      logger.log(`    ${logger.cyan(name)}${loc}`);
    }
  }

  logger.dim_(`\n  Completed in ${duration}ms\n`);
}

interface BuildContentOptions {
  existingContent: string | null;
  newVars: string[];
  presentVars: string[];
  foundVarsMap: Map<string, EnvVarReference>;
  envVars: Map<string, EnvVarDefinition>;
  withComments: boolean;
}

function buildExampleContent(opts: BuildContentOptions): string {
  const { existingContent, newVars, foundVarsMap, envVars, withComments } = opts;

  // If we're appending to existing file
  if (existingContent !== null && newVars.length > 0) {
    const additions = newVars
      .sort()
      .map(name => formatVar(name, foundVarsMap.get(name), envVars, withComments))
      .join('\n');

    return existingContent.trimEnd() + '\n\n# Added by env-doctor init\n' + additions + '\n';
  }

  // Building fresh file
  const allNames = [...new Set([...foundVarsMap.keys(), ...envVars.keys()])].sort();
  const lines: string[] = [
    '# Environment Variables',
    '# Generated by env-doctor init — do not commit real values',
    '',
  ];

  for (const name of allNames) {
    lines.push(formatVar(name, foundVarsMap.get(name), envVars, withComments));
  }

  return lines.join('\n') + '\n';
}

function formatVar(
  name: string,
  ref: EnvVarReference | undefined,
  envVars: Map<string, EnvVarDefinition>,
  withComments: boolean
): string {
  // Use placeholder from .env value (with redaction) if available
  const def = envVars.get(name);
  const placeholder = def?.value ? `# ${def.value}` : '';

  const comment = withComments && ref
    ? `  # referenced in ${ref.file}:${ref.line}`
    : '';

  return `${name}=${placeholder}${comment}`;
}
